version: '3.5'

services:
  quarkus-service:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.native
    image: code-with-quarkus-3:native
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://host.docker.internal:5434/postgres
    ports:
      - "8080:8080"
    depends_on:
      quarkus-db:
        condition: service_healthy
    restart: always
    networks:
      - quarkus

  quarkus-db:
    image: "postgres:latest"
    volumes:
      - ./postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quarkus"]
      interval: 40s
      timeout: 40s
      retries: 10
    ports:
      - "5434:5432"
    restart: always
    networks:
      - quarkus

networks:
  quarkus:
    driver: bridge
