version: '3.5'

volumes:
  frutadatabase:

services:
  quarkus-service:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.native
    image: docker-database-1:native
    mem_limit: 128m
    environment:
      - QUARKUS_DATASOURCE_URL=jdbc:postgresql://localhost:5432/frutasdb
    ports:
      - "8080:8080"
    networks:
      - quarkus

  quarkus-db:
    image: "postgres:14"
    mem_limit: 128m
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - quarkus

networks:
  quarkus:
    driver: bridge
